### DISCUSSION TITLE
Docker

### DISCUSSION THREAD

**Discussion by samuelds** [gildor2/UEViewer#295] [Ideas]
Hi,

You can create docker image ?

**Comment by gildor2** [comment]
What's docker, who can create it, and why?

**Reply by samuelds** [reply]
All information here : https://docs.docker.com/compose/gettingstarted/

**Reply by samuelds** [reply]
I can do it, but I need the dependency list to install on linux to run your script

**Comment by Blenux** [comment]
[Containerized Applications
](https://en.wikipedia.org/wiki/Docker_(software))

**Comment by samuelds** [comment]
Im start create docker :

Dockerfile
```
FROM alpine:latest

RUN apk add --no-cache sdl2 zlib libpng wget &&\
    wget -O /home/umodel https://github.com/gildor2/UEViewer/raw/master/umodel &&\
    chmod -R 777 /home/umodel
```

docker-compose.yml
```
version: "3"

services:
    
    umodel:
        container_name: umodel
        build:
          context:  .
          dockerfile: Dockerfile
        command: /home/umodel -path=/home/unpack -out=/home/images
        volumes:
          - ./data/unpack:/home/unpack
          - ./data/images:/home/images
```

On 'docker compose up' : 

```
[+] Running 1/0
 - Container umodel  Recreated                                                                                                     0.1s 
Attaching to umodel
umodel  | exec /home/umodel: no such file or directory
umodel exited with code 1
```
